# Generated by Django 5.0.6 on 2025-01-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MC', 'Mens Clothes'), ('WC', 'Womens Clothes'), ('KC', 'Kids Clothes'), ('JW', 'Jewelry'), ('SH', 'Shoes'), ('BG', 'Bags'), ('TY', 'Toys'), ('AC', 'Accessories'), ('EI', 'Electric Items')], max_length=2),
        ),
    ]
