# Generated by Django 5.0.6 on 2025-03-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
