# Generated by Django 5.0.6 on 2025-03-20 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_payment_payment_method_orderplaced_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_shipping_address', to='app.customer'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_customer', to='app.customer'),
        ),
    ]
