# Generated by Django 5.0.6 on 2025-03-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_orderplaced_shipping_address_and_more'),
    ]

    operations = [
    ]
