# Generated by Django 5.0.6 on 2025-03-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20250330_1739'),
    ]

    operations = [
    ]
