# Generated by Django 5.0.6 on 2025-03-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_amount_paid_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
